//! Ideal ↔ isogeny correspondence (Deuring correspondence helpers).
//! Ported from `src/id2iso/ref/lvlx/{id2iso.c,dim2id2iso.c}`.

use std::sync::OnceLock;

use crate::ec::biextension::ec_dlog_2_tate;
use crate::ec::*;
use crate::mp::{mp_invert_matrix, Digit};
use crate::precomp::{
    curves_with_endomorphisms, extremal_orders, maxord_o0, quatalg_pinfty, NWORDS_ORDER,
    QUAT_PRIMALITY_NUM_ITER, TORSION_EVEN_POWER, TORSION_PLUS_2POWER,
};
use crate::quaternion::*;

mod dim2;
pub use dim2::*;

// ---------------------------------------------------------------------------
// Precomp aliases (mirrors C macros in endomorphism_action.h / quaternion_data.h).

#[inline]
pub fn action_i() -> &'static IbzMat2x2 {
    &curves_with_endomorphisms()[0].action_i
}
#[inline]
pub fn action_j() -> &'static IbzMat2x2 {
    &curves_with_endomorphisms()[0].action_j
}
#[inline]
pub fn action_gen2() -> &'static IbzMat2x2 {
    &curves_with_endomorphisms()[0].action_gen2
}
#[inline]
pub fn action_gen3() -> &'static IbzMat2x2 {
    &curves_with_endomorphisms()[0].action_gen3
}
#[inline]
pub fn action_gen4() -> &'static IbzMat2x2 {
    &curves_with_endomorphisms()[0].action_gen4
}

/// `2^TORSION_EVEN_POWER` as an Ibz (lazy-initialized; matches C's
/// `TORSION_PLUS_2POWER` precomp).
pub fn torsion_plus_2power() -> &'static Ibz {
    static T: OnceLock<Ibz> = OnceLock::new();
    T.get_or_init(|| {
        let mut z = Ibz::default();
        ibz_copy_digits(&mut z, TORSION_PLUS_2POWER);
        z
    })
}

/// Standard parameters for `quat_represent_integer` (matches C's
/// `QUAT_represent_integer_params` static).
pub fn quat_represent_integer_params() -> QuatRepresentIntegerParams {
    QuatRepresentIntegerParams {
        algebra: quatalg_pinfty(),
        order: &extremal_orders()[0],
        primality_test_iterations: QUAT_PRIMALITY_NUM_ITER as i32,
    }
}

// ---------------------------------------------------------------------------
// id2iso.c

/// `[x]P + [y]Q` where (x,y) are big integers and P, Q ∈ E[2ᶠ].
pub fn ec_biscalar_mul_ibz_vec(
    res: &mut EcPoint,
    scalar_vec: &IbzVec2,
    f: i32,
    pq: &EcBasis,
    curve: &EcCurve,
) {
    let mut scalars = [[0 as Digit; NWORDS_ORDER]; 2];
    ibz_to_digits(&mut scalars[0], &scalar_vec[0]);
    ibz_to_digits(&mut scalars[1], &scalar_vec[1]);
    *res = ec_biscalar_mul(&scalars[0], &scalars[1], f, pq, curve).unwrap();
}

/// Given an O₀-ideal of norm 2ᶠ, compute (s₀, s₁) such that the kernel
/// of the corresponding isogeny is generated by [s₀]P + [s₁]Q for the
/// canonical basis (P, Q) of E₀[2ᶠ].
pub fn id2iso_ideal_to_kernel_dlogs_even(vec: &mut IbzVec2, lideal: &QuatLeftIdeal) {
    let mut tmp = Ibz::default();
    let mut mat = ibz_mat_2x2_init();

    {
        let mut alpha = QuatAlgElem::default();
        let ok = quat_lideal_generator(&mut alpha, lideal, quatalg_pinfty());
        debug_assert!(ok != 0);
        let a = alpha.clone();
        quat_alg_conj(&mut alpha, &a);

        let mut coeffs = ibz_vec_4_init();
        quat_change_to_o0_basis(&mut coeffs, &alpha);

        let g2 = action_gen2();
        let g3 = action_gen3();
        let g4 = action_gen4();
        for i in 0..2 {
            mat[i][i] += &coeffs[0];
            for j in 0..2 {
                ibz_mul(&mut tmp, &g2[i][j], &coeffs[1]);
                mat[i][j] += &tmp;
                ibz_mul(&mut tmp, &g3[i][j], &coeffs[2]);
                mat[i][j] += &tmp;
                ibz_mul(&mut tmp, &g4[i][j], &coeffs[3]);
                mat[i][j] += &tmp;
            }
        }
    }

    {
        let norm = &lideal.norm;
        ibz_mod(&mut vec[0], &mat[0][0], norm);
        ibz_mod(&mut vec[1], &mat[1][0], norm);
        ibz_gcd(&mut tmp, &vec[0], &vec[1]);
        if ibz_is_even(&tmp) {
            ibz_mod(&mut vec[0], &mat[0][1], norm);
            ibz_mod(&mut vec[1], &mat[1][1], norm);
        }
        #[cfg(debug_assertions)]
        {
            ibz_gcd(&mut tmp, &vec[0], norm);
            let v1 = vec[1].clone();
            let t = tmp.clone();
            ibz_gcd(&mut tmp, &v1, &t);
            debug_assert!(ibz_cmp(&tmp, ibz_const_one()) == 0);
        }
    }
}

/// Apply a 2×2 matrix to a basis of E[2ᶠ] in place.
pub fn matrix_application_even_basis(
    bas: &mut EcBasis,
    e: &EcCurve,
    mat: &mut IbzMat2x2,
    f: i32,
) -> Option<()> {
    let mut s0 = [0 as Digit; NWORDS_ORDER];
    let mut s1 = [0 as Digit; NWORDS_ORDER];
    let mut tmp = Ibz::default();
    let mut pow_two = Ibz::default();
    ibz_pow(&mut pow_two, ibz_const_two(), f as u32);

    let tmp_bas = *bas;

    for i in 0..2 {
        for j in 0..2 {
            let m = mat[i][j].clone();
            ibz_mod(&mut mat[i][j], &m, &pow_two);
        }
    }

    // R = [a]P + [b]Q
    ibz_to_digits(&mut s0, &mat[0][0]);
    ibz_to_digits(&mut s1, &mat[1][0]);
    bas.p = ec_biscalar_mul(&s0, &s1, f, &tmp_bas, e).unwrap();

    // S = [c]P + [d]Q
    ibz_to_digits(&mut s0, &mat[0][1]);
    ibz_to_digits(&mut s1, &mat[1][1]);
    bas.q = ec_biscalar_mul(&s0, &s1, f, &tmp_bas, e).unwrap();

    // R - S = [a-c]P + [b-d]Q
    ibz_sub(&mut tmp, &mat[0][0], &mat[0][1]);
    let t = tmp.clone();
    ibz_mod(&mut tmp, &t, &pow_two);
    ibz_to_digits(&mut s0, &tmp);
    ibz_sub(&mut tmp, &mat[1][0], &mat[1][1]);
    let t = tmp.clone();
    ibz_mod(&mut tmp, &t, &pow_two);
    ibz_to_digits(&mut s1, &tmp);
    bas.pmq = ec_biscalar_mul(&s0, &s1, f, &tmp_bas, e)?;
    Some(())
}

/// Apply an endomorphism `theta` (an algebra element in the order
/// `EXTREMAL_ORDERS[index_alternate_curve]`) to a basis of E[2ᶠ].
pub fn endomorphism_application_even_basis(
    bas: &mut EcBasis,
    index_alternate_curve: usize,
    e: &EcCurve,
    theta: &QuatAlgElem,
    f: i32,
) {
    let mut tmp = Ibz::default();
    let mut coeffs = ibz_vec_4_init();
    let mut mat = ibz_mat_2x2_init();
    let mut content = Ibz::default();

    quat_alg_make_primitive(
        &mut coeffs,
        &mut content,
        theta,
        &extremal_orders()[index_alternate_curve].order,
    );
    debug_assert!(ibz_is_odd(&content));

    for i in 0..2 {
        for j in 0..2 {
            ibz_set(&mut mat[i][j], 0);
        }
    }

    let cwe = &curves_with_endomorphisms()[index_alternate_curve];
    for i in 0..2 {
        mat[i][i] += &coeffs[0];
        for j in 0..2 {
            ibz_mul(&mut tmp, &cwe.action_gen2[i][j], &coeffs[1]);
            mat[i][j] += &tmp;
            ibz_mul(&mut tmp, &cwe.action_gen3[i][j], &coeffs[2]);
            mat[i][j] += &tmp;
            ibz_mul(&mut tmp, &cwe.action_gen4[i][j], &coeffs[3]);
            mat[i][j] += &tmp;
            mat[i][j] *= &content;
        }
    }

    matrix_application_even_basis(bas, e, &mut mat, f);
}

/// Reverse direction: from kernel coefficients (vec₂) to an O₀-ideal of
/// norm 2ᶠ.
pub fn id2iso_kernel_dlogs_to_ideal_even(lideal: &mut QuatLeftIdeal, vec2: &IbzVec2, f: i32) {
    let mut two_pow = Ibz::default();
    let mut vec = ibz_vec_2_init();

    if f as usize == TORSION_EVEN_POWER {
        two_pow.clone_from(torsion_plus_2power());
    } else {
        ibz_pow(&mut two_pow, ibz_const_two(), f as u32);
    }

    {
        let mut mat = ibz_mat_2x2_init();
        mat[0][0].clone_from(&vec2[0]);
        mat[1][0].clone_from(&vec2[1]);

        ibz_mat_2x2_eval(&mut vec, action_j(), vec2);
        mat[0][1].clone_from(&vec[0]);
        mat[1][1].clone_from(&vec[1]);

        ibz_mat_2x2_eval(&mut vec, action_gen4(), vec2);
        mat[0][1] += &vec[0];
        mat[1][1] += &vec[1];

        let m01 = mat[0][1].clone();
        ibz_mod(&mut mat[0][1], &m01, &two_pow);
        let m11 = mat[1][1].clone();
        ibz_mod(&mut mat[1][1], &m11, &two_pow);

        let mut inv = ibz_mat_2x2_init();
        let inv_ok = ibz_mat_2x2_inv_mod(&mut inv, &mat, &two_pow);
        debug_assert!(inv_ok != 0);

        ibz_mat_2x2_eval(&mut vec, action_i(), vec2);
        let v = vec.clone();
        ibz_mat_2x2_eval(&mut vec, &inv, &v);
    }

    // gen = a − i + b·(j + (1+k)/2) where (a,b) = vec.
    let mut gen = QuatAlgElem::default();
    ibz_set(&mut gen.denom, 2);
    ibz_add(&mut gen.coord[0], &vec[0], &vec[0]);
    ibz_set(&mut gen.coord[1], -2);
    ibz_add(&mut gen.coord[2], &vec[1], &vec[1]);
    gen.coord[3].clone_from(&vec[1]);
    gen.coord[0] += &vec[1];

    quat_lideal_create(lideal, &gen, &two_pow, maxord_o0(), quatalg_pinfty());
    debug_assert!(ibz_cmp(&lideal.norm, &two_pow) == 0);
}

fn change_of_basis_matrix_tate_impl(
    mat: &mut IbzMat2x2,
    b1: &EcBasis,
    b2: &EcBasis,
    e: &mut EcCurve,
    f: i32,
    invert: bool,
) {
    let mut x1 = [0 as Digit; NWORDS_ORDER];
    let mut x2 = [0 as Digit; NWORDS_ORDER];
    let mut x3 = [0 as Digit; NWORDS_ORDER];
    let mut x4 = [0 as Digit; NWORDS_ORDER];

    if invert {
        debug_assert!(test_basis_order_twof(b1, e, TORSION_EVEN_POWER as i32));
        ec_dlog_2_tate(&mut x1, &mut x2, &mut x3, &mut x4, b1, b2, e, f);
        mp_invert_matrix(&mut x1, &mut x2, &mut x3, &mut x4, f, NWORDS_ORDER);
    } else {
        debug_assert!(test_basis_order_twof(b2, e, TORSION_EVEN_POWER as i32));
        ec_dlog_2_tate(&mut x1, &mut x2, &mut x3, &mut x4, b2, b1, e, f);
    }

    #[cfg(debug_assertions)]
    {
        let e_full = TORSION_EVEN_POWER as i32;
        let e_diff = e_full - f;
        let mut test;
        let mut test2 = EcPoint::default();
        if invert {
            test = ec_biscalar_mul(&x1, &x2, f, b2, e).unwrap();
            ec_dbl_iter(&mut test2, e_diff, &b1.p, e);
            debug_assert!(test.is_equal_ct(&test2) != 0);
            test = ec_biscalar_mul(&x3, &x4, f, b2, e).unwrap();
            ec_dbl_iter(&mut test2, e_diff, &b1.q, e);
            debug_assert!(test.is_equal_ct(&test2) != 0);
        } else {
            test = ec_biscalar_mul(&x1, &x2, f, b2, e).unwrap();
            let s = test;
            ec_dbl_iter(&mut test, e_diff, &s, e);
            debug_assert!(test.is_equal_ct(&b1.p) != 0);
            test = ec_biscalar_mul(&x3, &x4, f, b2, e).unwrap();
            let s = test;
            ec_dbl_iter(&mut test, e_diff, &s, e);
            debug_assert!(test.is_equal_ct(&b1.q) != 0);
        }
    }

    ibz_copy_digits(&mut mat[0][0], &x1);
    ibz_copy_digits(&mut mat[1][0], &x2);
    ibz_copy_digits(&mut mat[0][1], &x3);
    ibz_copy_digits(&mut mat[1][1], &x4);
}

/// Find `mat` such that `(mat·v)·B₂ = v·B₁`.
pub fn change_of_basis_matrix_tate(
    mat: &mut IbzMat2x2,
    b1: &EcBasis,
    b2: &EcBasis,
    e: &mut EcCurve,
    f: i32,
) {
    change_of_basis_matrix_tate_impl(mat, b1, b2, e, f, false);
}

/// Find `mat` such that `(mat·v)·B₁ = [2^{e−f}]·v·B₂`.
pub fn change_of_basis_matrix_tate_invert(
    mat: &mut IbzMat2x2,
    b1: &EcBasis,
    b2: &EcBasis,
    e: &mut EcCurve,
    f: i32,
) {
    change_of_basis_matrix_tate_impl(mat, b1, b2, e, f, true);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::precomp::{basis_even, curve_e0};

    #[test]
    fn endomorphism_application_smoke() {
        // Apply the identity endomorphism (1 + 0i + 0j + 0k) to the
        // canonical E0 basis; result must equal the input.
        let mut bas = *basis_even();
        let e0 = *curve_e0();
        let mut theta = QuatAlgElem::default();
        quat_alg_elem_set(&mut theta, 1, 1, 0, 0, 0);
        endomorphism_application_even_basis(&mut bas, 0, &e0, &theta, TORSION_EVEN_POWER as i32);
        // Compare projectively.
        assert_ne!(bas.p.is_equal_ct(&basis_even().p), 0);
        assert_ne!(bas.q.is_equal_ct(&basis_even().q), 0);
    }

    #[test]
    fn ideal_kernel_roundtrip() {
        // ker → ideal → ker should be the same kernel up to scaling.
        let f = 8;
        let vec_in: IbzVec2 = [Ibz::from(3), Ibz::from(1)];
        let mut lideal = QuatLeftIdeal::default();
        id2iso_kernel_dlogs_to_ideal_even(&mut lideal, &vec_in, f);
        let mut two_f = Ibz::default();
        ibz_pow(&mut two_f, ibz_const_two(), f as u32);
        assert!(ibz_cmp(&lideal.norm, &two_f) == 0);

        let mut vec_out = ibz_vec_2_init();
        id2iso_ideal_to_kernel_dlogs_even(&mut vec_out, &lideal);
        // (vec_out₀, vec_out₁) should generate the same cyclic subgroup as (3,1)
        // i.e. 3·vec_out₁ ≡ vec_out₀ (mod 2^f) up to scaling.
        let mut det = Ibz::default();
        ibz_mat_2x2_det_from_ibz(&mut det, &vec_in[0], &vec_out[0], &vec_in[1], &vec_out[1]);
        let r = ibz_mod_ui(&det, 1u64 << f);
        assert_eq!(r, 0, "kernel directions differ: {vec_in:?} vs {vec_out:?}");
    }
}
